.\"     Title: 
   /home/waldi/debian/kernel/release/linux-2.6/linux-2.6-2.6.26/debian/build/source//include/net/mac80211.h
  
.\"    Author: Johannes Berg <johannes@sipsolutions.net>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 09/10/2008
.\"    Manual: The basic mac80211 driver interface
.\"    Source: 
.\"
.TH "/HOME/WALDI/DEBI" "1" "09/10/2008" "" "The basic mac80211 driver inte"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"

___/home/waldi/debian/kernel/release/linux-2.6/linux-2.6-2.6.26/debian/build/source//include/net/mac80211.h
__ \- Document generation inconsistency
.SH "OOPS"
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
Warning
.PP
The template for this document tried to insert the structured comment from the file
\fI/home/waldi/debian/kernel/release/linux\-2\&.6/linux\-2\&.6\-2\&.6\&.26/debian/build/source//include/net/mac80211\&.h\fR
at this point, but none was found\&. This dummy section is inserted to allow generation to continue\&.
.SH "AUTHOR"
.PP
\fBJohannes Berg\fR <\&johannes@sipsolutions.net\&>
.sp -1n
.IP "" 4
Author.
.SH "COPYRIGHT"
Copyright \(co 2007, 2008 Johannes Berg
.br
.PP
This documentation is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
.PP
This documentation is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with this documentation; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
.PP
For more details see the file COPYING in the source distribution of Linux.
.sp
