#
# Makefile for ALSA
#

snd-sgi-o2-objs := sgio2audio.o ad1843.o
snd-au1x00-objs := au1x00.o

# Toplevel Module Dependency
obj-$(CONFIG_SND_AU1X00) += snd-au1x00.o
obj-$(CONFIG_SND_SGI_O2) += snd-sgi-o2.o
