/*
 * Automatically generated C config: don't edit
 */
#define AUTOCONF_INCLUDED

/*
 * Vendor/Product Selection
 */

/*
 * Select the Vendor you wish to target
 */
#undef  CONFIG_DEFAULTS_3COM
#undef  CONFIG_DEFAULTS_ADI
#undef  CONFIG_DEFAULTS_AKIZUKI
#undef  CONFIG_DEFAULTS_APPLE
#undef  CONFIG_DEFAULTS_ARCTURUS
#undef  CONFIG_DEFAULTS_ARNEWSH
#define CONFIG_DEFAULTS_ATMARKTECHNO 1
#undef  CONFIG_DEFAULTS_ATMEL
#undef  CONFIG_DEFAULTS_AVNET
#undef  CONFIG_DEFAULTS_CIRRUS
#undef  CONFIG_DEFAULTS_COGENT
#undef  CONFIG_DEFAULTS_CONEXANT
#undef  CONFIG_DEFAULTS_CWLINUX
#undef  CONFIG_DEFAULTS_CYBERGUARD
#undef  CONFIG_DEFAULTS_CYTEK
#undef  CONFIG_DEFAULTS_EXYS
#undef  CONFIG_DEFAULTS_FEITH
#undef  CONFIG_DEFAULTS_FUTURE
#undef  CONFIG_DEFAULTS_GDB
#undef  CONFIG_DEFAULTS_HITACHI
#undef  CONFIG_DEFAULTS_IMT
#undef  CONFIG_DEFAULTS_INSIGHT
#undef  CONFIG_DEFAULTS_INTEL
#undef  CONFIG_DEFAULTS_KENDINMICREL
#undef  CONFIG_DEFAULTS_LEOX
#undef  CONFIG_DEFAULTS_MECEL
#undef  CONFIG_DEFAULTS_MIDAS
#undef  CONFIG_DEFAULTS_MOTOROLA
#undef  CONFIG_DEFAULTS_NEC
#undef  CONFIG_DEFAULTS_NETSILICON
#undef  CONFIG_DEFAULTS_NETBURNER
#undef  CONFIG_DEFAULTS_NINTENDO
#undef  CONFIG_DEFAULTS_OPENCORES
#undef  CONFIG_DEFAULTS_PROMISE
#undef  CONFIG_DEFAULTS_SNEHA
#undef  CONFIG_DEFAULTS_SSV
#undef  CONFIG_DEFAULTS_SWARM
#undef  CONFIG_DEFAULTS_SAMSUNG
#undef  CONFIG_DEFAULTS_SECUREEDGE
#undef  CONFIG_DEFAULTS_SIGNAL
#undef  CONFIG_DEFAULTS_SNAPGEAR
#undef  CONFIG_DEFAULTS_SOEKRIS
#undef  CONFIG_DEFAULTS_SONY
#undef  CONFIG_DEFAULTS_STRAWBERRYLINUX
#undef  CONFIG_DEFAULTS_TI
#undef  CONFIG_DEFAULTS_TELEIP
#undef  CONFIG_DEFAULTS_TRISCEND
#undef  CONFIG_DEFAULTS_VIA
#undef  CONFIG_DEFAULTS_WEISS
#undef  CONFIG_DEFAULTS_XILINX
#undef  CONFIG_DEFAULTS_SENTEC

/*
 * Select the Product you wish to target
 */
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_ARMADILLO_210_BASE
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_ARMADILLO_210_RECOVER
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_ARMADILLO_220_BASE
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_ARMADILLO_220_RECOVER
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_ARMADILLO_230_BASE
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_ARMADILLO_230_RECOVER
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_ARMADILLO_240_BASE
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_ARMADILLO_240_RECOVER
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_ARMADILLO_300
#define CONFIG_DEFAULTS_ATMARKTECHNO_ARMADILLO_420 1
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_ARMADILLO_420_WLAN_AWL12
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_ARMADILLO_420_WLAN_AWL13
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_ARMADILLO_440
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_ARMADILLO_460
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_ARMADILLO_500
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_ARMADILLO_500_FX_BASE
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_ARMADILLO_500_FX_DEV
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_ARMADILLO_810
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_ARMADILLO_840
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_ARMADILLO_9
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_ARMADILLO_9_PCMCIA
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_ARMADILLO_IOTG_STD
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_SUZAKU_V_SZ310
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_SUZAKU_V_SZ310_SID
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_SUZAKU_V_SZ310_SIL
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_SUZAKU_V_SZ310_SIL_GPIO
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_SUZAKU_V_SZ410
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_SUZAKU_V_SZ410_SID
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_SUZAKU_V_SZ410_SIL
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_SUZAKU_V_SZ410_SIL_GPIO
#undef  CONFIG_DEFAULTS_ATMARKTECHNO_SUZAKU_V_SZ410_SIV

/*
 * Kernel/Library/Defaults Selection
 */

/*
 * Kernel is linux-2.6.x
 */
#define CONFIG_DEFAULTS_KERNEL_2_6 1
#define CONFIG_DEFAULTS_CROSSDEV_DEFAULT 1
#undef  CONFIG_DEFAULTS_CROSSDEV_ARM_VFP
#undef  CONFIG_DEFAULTS_CROSSDEV_ARM
#undef  CONFIG_DEFAULTS_CROSSDEV_ARMEL
#undef  CONFIG_DEFAULTS_CROSSDEV_ARMHF
#undef  CONFIG_DEFAULTS_CROSSDEV_ARMNOMMU
#undef  CONFIG_DEFAULTS_CROSSDEV_COMMON
#undef  CONFIG_DEFAULTS_CROSSDEV_H8300
#undef  CONFIG_DEFAULTS_CROSSDEV_HOST
#undef  CONFIG_DEFAULTS_CROSSDEV_I386
#undef  CONFIG_DEFAULTS_CROSSDEV_I960
#undef  CONFIG_DEFAULTS_CROSSDEV_M68KNOMMU
#undef  CONFIG_DEFAULTS_CROSSDEV_MICROBLAZE
#undef  CONFIG_DEFAULTS_CROSSDEV_MIPS
#undef  CONFIG_DEFAULTS_CROSSDEV_POWERPC
#undef  CONFIG_DEFAULTS_CROSSDEV_SH
#define CONFIG_DEFAULTS_LIBC_NONE 1
#undef  CONFIG_DEFAULTS_LIBC_GLIBC
#undef  CONFIG_DEFAULTS_LIBC_UC_LIBC
#undef  CONFIG_DEFAULTS_LIBC_UCLIBC
#undef  CONFIG_DEFAULTS_OVERRIDE
#undef  CONFIG_DEFAULTS_KERNEL
#undef  CONFIG_DEFAULTS_VENDOR
#undef  CONFIG_DEFAULTS_VENDOR_UPDATE
