#!/bin/sh

logger -p user.info "thermal state passive."
logger -p user.info "set the 3G in nomal mode."

# set 3G Nomal mode
echo 1 > /sys/class/gpio/W_DISABLE_3G/value

ifdown usb0
ifup usb0
ifplugd -i usb0 -p -q
